language: ruby
bundler_args: --without development
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "bundle exec rake refinery:testing:dummy_app"
script:
  - "DISPLAY=:99.0 bundle exec rspec spec"
notifications:
  email: true
  irc:
    use_notice: true
    skip_join: true
    channels:
      - "irc.freenode.org#refinerycms"
  campfire:
    on_success: always
    on_failure: always
    rooms:
      - secure: "JaX+Ckvdd2wqL2bD6t8PHvMDBHxWBlCrkBKPcDKxV0t0DOwzzzwxMryVqcRi\nPsmM/zvmWFATDyRmivhNOpu4lRg9RytSroxZ9nkmbLDqjCyEAZ6tv4yZXME/\nPaxPwmfwgS9g8TKjj3lSWS7rEpqqg0D5S0XIfIHrj6KB6LUmFHc="
env:
  - DB=postgresql
  - DB=mysql
matrix:
  allow_failures:
    - rvm: rbx-19mode
rvm:
  - 2.0.0
  - 1.9.3
  - rbx-19mode
  - jruby-19mode
