language: ruby
before_install:
  - 'if [[ "$TRAVIS_RUBY_VERSION" =~ "jruby" ]] ; then gem update --system ; fi'
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "bundle exec rake refinery:testing:dummy_app > /dev/null"
script:
  - "DISPLAY=:99.0 bundle exec rspec spec"
notifications:
  email: true
env:
  - DB=postgresql
  - DB=mysql
matrix:
  allow_failures:
    - rvm: rbx-18mode
    - rvm: rbx-19mode
    - rvm: jruby-19mode
    - rvm: jruby-18mode
rvm:
  - 2.0.0
  - 1.9.3
  - 1.8.7
  - rbx-19mode
  - jruby-19mode
  - rbx-18mode
  - jruby-18mode
